set -ga terminal-overrides ",xterm-256color*:Tc"
set -g mouse on
set -g detach-on-destroy off

bind-key h split-pane -hl 71
bind-key v split-pane -vl 11

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin "arcticicestudio/nord-tmux"

run '~/.tmux/plugins/tpm/tpm'
