source ~/.config/nvim/vim-plug.vim
source ~/.config/nvim/settings.vim
source ~/.config/nvim/plugins.vim
source ~/.config/nvim/custom-remaps.vim
source ~/.config/nvim/fugitive.vim
source ~/.config/nvim/colorscheme.vim
source ~/.config/nvim/airline.vim
source ~/.config/nvim/fzf.vim
source ~/.config/nvim/coc.vim
source ~/.config/nvim/nerdtree.vim
